Update hdr_explainer.md with latest status of video-* features
w3c/media-capabilities pull request #210
Opened 2024-01-12 17:06 UTC by chrisn

2025-06-12 11:37 UTC, marcoscaceres commented on hdr_explainer.md
> +The sizing video-* prefixed features are still under discussion, see CSS issues [#4471](https://github.com/w3c/csswg-drafts/issues/4471), [#4678](https://github.com/w3c/csswg-drafts/pull/4678), [#504
```suggestion
The sizing video-* prefixed features are still under discussion, see CSS issues [#4678](https://github.com/w3c/csswg-drafts/pull/4678), [#5044](https://github.com/w3c/csswg-drafts/issues/5044), and [#6891](https://github.com/w3c/csswg-drafts/issues/6891). Rather than add `video-width`, `video-height`, and `video-resolution` media queries, the current proposal is to expose a `deviceVideoPixelRatio` property.
```

2025-06-12 19:09 UTC, chrisn commented
@markafoltz Is this explainer update OK to merge?

2025-06-20 19:09 UTC, markafoltz requested changes

2025-06-20 19:09 UTC, markafoltz commented on hdr_explainer.md
> +As of 2020/21, here's the unofficial status of user agent implementations for the above:
This section needs to be updated per the following:

- https://caniuse.com/mdn-css_at-rules_media_dynamic-range
- https://caniuse.com/mdn-css_at-rules_media_video-dynamic-range
- https://chromestatus.com/feature/6640863931269120
-

2025-06-23 16:55 UTC, markafoltz commented
I updated the browser support section, merging.

2025-06-23 16:56 UTC, merged